### ISSUE TITLE
some error about train_eval_CUB.sh

### ISSUE THREAD

**Issue by Jingwenchenhdu** [pedro-morgado/score-zeroshot#1]
I  carry out train_eval_CUB.sh use linux,inception_v1.caffemodel. When carry out to
# Evaluate SCoRe model
python score_eval.py ${MODEL_DIR} CUB Attributes GoogLeNet

I meet this problem and i can't slove it.
Layer SCoRe/obj/fc_target (weights) initialized
Traceback (most recent call last):
  File "score_eval.py", line 139, in <module>
    main(parse_cmd())
  File "score_eval.py", line 134, in main
    mca, acc, semAcc, semAUC = evaluate_model(classes, constrains, LMDBs, args)
  File "score_eval.py", line 111, in evaluate_model
    semAcc[mode], semAUC[mode] = eval_semantics(scores, semantics, args)
  File "score_eval.py", line 50, in eval_semantics
    acc[s] = (pred*(lbl-0.5) > 0).astype(float).mean()
ValueError: operands could not be broadcast together with shapes (10,) (2933,) 

 Can you give me some suggestion?

**Comment by hoseong-kim** [comment]
Hi, @Jingwenchenhdu,

I'd have exactly the same problem with you, but now I fixed it.
The error indicates that the size of "pred"(related to predicted ) is 10 and that of "lbl"(related to the ground truth) is 2933.
You might solve this problem by deleting your current "LMDBs" folder and then run "prep_lmdbs.sh" again to generate lmdb files.
